### ISSUE TITLE
Allow to pass TValue directly in DataLoader.Set

### ISSUE THREAD

**Issue by namnm** [ChilliCream/greendonut#30]
**Is your feature request related to a problem? Please describe.**
Now when I get a list from db and want to set them into the loader, I need to convert the values into `Task<TValue>`. We should have another method which allows to pass `TValue` directly: `public IDataLoader<TKey, TValue> Set(TKey key, TValue value);`

**Comment by rstaib** [comment]
Thank you for proposing this. It is indeed a valid use case. Therefore, we will provide an extension method for `IDataLoader<TKey, TValue>` shortly.

**Comment by rstaib** [comment]
Is now part of the _master_ branch and going to be part of version `1.1.0` shortly.
